backend:
  name: github
  repo: superkp/superkp.github.io   # 用户名/仓库名
  branch: master
  base_url: https://decap-proxy.supekp.workers.dev   # 修正为你部署的 Worker 地址

media_folder: "content/post/{{slug}}"       # 每篇文章的媒体文件放在自己文章的文件夹
public_folder: "/images/uploads/{{slug}}"   # 对应的公开路径

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/post"          # 文章存放的主目录
    create: true
    slug: "{{slug}}"                # 用 slug 创建文章文件夹
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Weight", name: "weight", widget: "number", default: 1 }
      - { label: "Body", name: "body", widget: "markdown" }
