backend:
  name: git-gateway
  branch: master                 # 文章提交的分支

media_folder: "static/images/uploads"   # 上传图片保存的位置
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/post"
    create: true
    # 这里用 nested，让 CMS 在新建时为每篇文章建立目录
    nested:
      depth: 100         # 允许目录嵌套
      summary: "{{title}}"
    slug: "{{slug}}"     # 每篇文章目录的名字
    path: "{{slug}}/index"   # 关键！新文章文件名固定为 index.md
    media_folder: ""     # 图片存在文章目录下
    public_folder: ""    # 图片引用相对路径
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Weight", name: "weight", widget: "number", default: 1 }
      - { label: "Body", name: "body", widget: "markdown" }