backend:
  name: github
  repo: superkp/superkp.github.io   # 用户名/仓库名
  branch: master
  base_url: https://decap-proxy.supekp.workers.dev   # 这个等会儿再改

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Weight", name: "weight", widget: "number", default: 1 }
      - { label: "Body", name: "body", widget: "markdown" }
